[platformio]
; libdeps_dir = /tmp/libdeps
; Note: Use EVN PLATFORMIO_BUILD_CACHE_DIR for build_cache_dir
extra_configs =
  lib/OGM-Common/platformio.base.ini
  lib/OGM-Common/platformio.rp2040.ini
  lib/OGM-Common/platformio.esp32.ini
  platformio.custom.ini

