# Check merging/building of OpenKNX knxprod for combination of all referenced module versions
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2024-2025 Cornelius Koepp

name: openknx-project-check
run-name: Checking OpenKNX Project
on: [push]
jobs:
  knxprod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore Project
        shell: pwsh
        run: |
          cd restore 
          ./Restore-Dependencies.ps1

      - name: Download OpenKNXproducer 3.6.2 and Verify
        run: mkdir OpenKNXproducer && cd OpenKNXproducer && echo '6afc36894e34c24575bf44034ebdddc47eec92dd8024a7e7ae18cda26f60d36fb710b5fefe3f5c6eeb0db465d2c1567bc558b395011bef1afa30a003bed39dfd *OpenKNXproducer-3.6.2.zip' > OpenKNXproducer.checksum && wget -q https://github.com/OpenKNX/OpenKNXproducer/releases/download/v3.6.2/OpenKNXproducer-3.6.2.zip && sha512sum OpenKNXproducer-3.6.2.zip && sha512sum -c OpenKNXproducer.checksum
      - name: Unzip OpenKNXproducer and Make Executable
        run: cd OpenKNXproducer && unzip OpenKNXproducer-3.6.2.zip || test -f tools/Linux/OpenKNXproducer && chmod u+x tools/Linux/OpenKNXproducer
      - name: Check OpenKNXproducer
        run: OpenKNXproducer/tools/Linux/OpenKNXproducer version || echo Ignore OpenKNXproducer always returning 1...

      - name: Install OpenKNXproducer
        run: cd OpenKNXproducer && cp -av tools/Linux/OpenKNXproducer /usr/local/bin/OpenKNXproducer

      - name: Create knxprod (DEV)
        run: OpenKNXproducer create --Debug -h include/knxprod.h src/StateEngine
      - name: Create knxprod (DFA16 Release)
        run: OpenKNXproducer create --Debug -h include/knxprod.h src/StateEngine-DFA16-Release

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv ~/.platformio/penv
          source ~/.platformio/penv/bin/activate
          pip install platformio          

      # - name: Build with PlatformIO
      #  run: pio run

      - name: OpenKNX Release Build
        run: pwsh ./scripts/Build-Release.ps1 DFA16-Release

      - name: Show Changed Files
        run: git diff
