# Check merging/building of OpenKNX knxprod for combination of all referenced module versions
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2024-2025 Cornelius Koepp

name: openknx-project-check
run-name: Checking OpenKNX Project
on: [push]
jobs:
  knxprod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore Project
        shell: pwsh
        run: |
          cd restore 
          ./Restore-Dependencies.ps1

      - name: Download OpenKNXproducer 3.3.4 and Verify
        run: mkdir OpenKNXproducer && cd OpenKNXproducer && echo '662f09fea9c8822e5dce744d12b31f65f1c6f84d24507c6596751c242f79c14aca7f09dc40add8999413eaa1cdd8b84b716836c2a1d5c3b9ce2f6bbdecea3388 *OpenKNXproducer-3.3.4.zip' > OpenKNXproducer.checksum && wget -q https://github.com/OpenKNX/OpenKNXproducer/releases/download/v3.3.4/OpenKNXproducer-3.3.4.zip && sha512sum OpenKNXproducer-3.3.4.zip && sha512sum -c OpenKNXproducer.checksum
      - name: Unzip OpenKNXproducer and Make Executable
        run: cd OpenKNXproducer && unzip OpenKNXproducer-3.3.4.zip || test -f tools/Linux/OpenKNXproducer && chmod u+x tools/Linux/OpenKNXproducer
      - name: Check OpenKNXproducer
        run: OpenKNXproducer/tools/Linux/OpenKNXproducer version || echo Ignore OpenKNXproducer always returning 1...

      - name: Create knxprod (DEV)
        run: OpenKNXproducer/tools/Linux/OpenKNXproducer create --Debug -h include/knxprod.h src/StateEngine
      - name: Create knxprod (DFA16 Release)
        run: OpenKNXproducer/tools/Linux/OpenKNXproducer create --Debug -h include/knxprod.h src/StateEngine-DFA16-Release
